# Generated by Django 4.0.1 on 2022-04-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_cart_cartitem_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
